spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///Users/stewartbarron/Desktop/Dev/Projects/Microservices/aruna/git-localconfig-repo
server:
  port: 8888
